status: true
dependencies:
  module:
    - jwt
id: jwt_rsa_key
label: 'JWT Rsa Key'
description: 'JWT rsa key'
key_type: jwt_rs
key_type_settings:
  algorithm: RS256
key_provider: file
key_provider_settings:
  file_location: ../jwt/jwt.key
  strip_line_breaks: false
key_input: none
key_input_settings: {  }
