status: true
dependencies:
  module:
    - jwt
    - serialization
    - user
id: entity.user
plugin_id: 'entity:user'
granularity: resource
configuration:
  methods:
    - GET
    - POST
    - DELETE
    - PATCH
  formats:
    - json
  authentication:
    - jwt_auth
