name: Install Nodehive CE Edition

on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  nodehive-ce-install:
    name: Nodehive CE Install
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.2']

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: db
          MYSQL_DATABASE: db
          MYSQL_USER: db
          MYSQL_PASSWORD: db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout Nodehive CE
        uses: actions/checkout@v2
        with:
          repository: NETNODEAG/nodehive-headless-cms-ce

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          composer install

      - name: Configure Drupal settings.
        run: |
          cp ${GITHUB_WORKSPACE}/.github/config/settings.php ${GITHUB_WORKSPACE}/web/sites/default/settings.php

      - name: Run install script
        run: |
          ${GITHUB_WORKSPACE}/install/install.sh --skip-composer
